version: 2
updates:
  - package-ecosystem: npm
    directory: /services
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
          - "@smithy/*"
      powertools:
        patterns:
          - "@aws-lambda-powertools/*"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"

  - package-ecosystem: terraform
    directory: /infra
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
